### ISSUE TITLE
FR: Setup Stripe iDeal payments

### ISSUE THREAD

**Issue by studiovlijmscherp** [edalzell/statamic-charge-issues#2]
We need to setup iDeal payments (https://stripe.com/docs/sources/ideal). iDeal uses Stripe Sources, can you explain how to implement this by using your addon?

**Comment by studiovlijmscherp** [comment]
Hi, okay. Sure, but where/how?

**Comment by edalzell** [comment]
No plans to implement this atm, going to close. If needed, please enter again in the [main repo](/edalzell/statamic-charge)
