### ISSUE TITLE
Control Panel throws error if there is no Stripe API Key

### ISSUE THREAD

**Issue by danfascia** [edalzell/statamic-charge-issues#4]
If you try to access the Charge tab on the left menu in the control panel after installing the add-on but no Stripe API Key, it throws a Control Panel error (Woops... etc...)

The add-on does not catch and handle the error on lack of API key at this stage.

Here's the output from debug mode:

`
Authentication in ApiRequestor.php line 220:
No API key provided. (HINT: set your API key using "Stripe::setApiKey(<API-KEY>)". You can generate API keys from the Stripe web interface. See https://stripe.com/api for details, or email support@stripe.com if you have any questions.`

**Comment by edalzell** [comment]
Fixed in https://github.com/edalzell/statamic-charge/commit/56febd88d910d699146666abdb5da46be549758f
