### ISSUE TITLE
Error loading settings page

### ISSUE THREAD

**Issue by justinwoolley98** [edalzell/statamic-charge-issues#5]
Hello,
I´ve bought a licence for charge and I installed as shown in the instructions. After installation, when I go to the location shown in the Instruction I always get an error message saying 

> ParseException in Parser.php line 444: Unable to parse at line 64 (near "width 33").

When I open cp/addons/charge/ it also gives me an error message saying: 

> Authentication in ApiRequestor.php line 313: No API key provided. (HINT: set your API key using "Stripe::setApiKey(<API-KEY>)". You can generate API keys from the Stripe web interface. See https://stripe.com/api for details, or email support@stripe.com if you have any questions.

But I can´t run the command as suggested in the error message.

Could you please give me any advice on how to correct the issue because I need this for a customer.

Regards

Justin Woolley

**Comment by justinwoolley98** [comment]
Statamic 2.9.8 and Charge 2.7.2

**Comment by edalzell** [comment]
To fix the second issue, please add `STRIPE_SECRET_KEY` and `STRIPE_PUBLIC_KEY` to your `.env` file. You can get your Stripe keys [here](https://dashboard.stripe.com/account/apikeys).

For the first issue, is there more of the stack trace in your Statamic log @justinwoolley98?

**Comment by edalzell** [comment]
Also @justinwoolley98, if you come on the Statamic Slack group, I can walk you through your issues.

**Comment by edalzell** [comment]
Fixed in https://github.com/edalzell/statamic-charge/commit/bca6764bbf618fa29a0d6cbc0a847e3917798bcb
